stores = {
    "ACV VERBOND": "Income",
    "A-PACK": "Income",
    "EINDEJAARSPREMIE": "Income",
    "JOBBONUS": "Income",
    "ACV-CSC METEA": "Income",

    "HOVENIERSTRAAT 134 LOKEREN": "House Rent",

    "LIDL": "Groceries",
    "COLRUYT": "Groceries",
    "ALDI": "Groceries",
    "ALBERT HEIJN": "Groceries",
    "MUCH MORE MARKET": "Groceries",

    "AVIA": "Mobility",
    "PARKING": "Mobility",
    "PARKEEREN": "Mobility",
    "DATS": "Mobility",
    "BRUSSELS SOUTH": "Mobility",
    "VLABEL": "Mobility",

    "MEDIA MARKT": "Shopping",
    "AMAZON": "Shopping",
    "BRICO": "Shopping",
    "ACTION": "Shopping",
    "KRUIDVAT": "Shopping",
    "HUBO": "Shopping",
    "ZARA": "Shopping",
    "H&M": "Shopping",
    "IKEA": "Shopping",
    "AVA": "Shopping",
    "KREFEL": "Shopping",
    "JYSK": "Shopping",
    "HEMA": "Shopping",

    "AMZN": "Shopping",
    "NEXT": "Shopping",
    "BOL.COM": "Shopping",
    "TEMU.COM":"Shopping",
    "SHEIN.COM": "Shopping",

    "TAKEAWAY.COM": "Bar & Restaurants",
    "CHEFDAG": "Bar & Restaurants",
    "ACTIEF": "Bar & Restaurants",
    "BURGER KING": "Bar & Restaurants",
    "DOMINOS": "Bar & Restaurants",
    "BAKKERIJ": "Bar & Restaurants",
    "EAT LOVE PIZZA": "Bar & Restaurants",
    "PIZZA HUT": "Bar & Restaurants",

    "KIDSLIFE": "Alimony",

    "LUMINUS": "Utilities",
    "WATERGROEP": "Utilities",
    "ACV OOST-VLAANDEREN": "Utilities",
    "PROXIMUS": "Utilities",

    "ARGENTA": "Insurance",

    "KINE VAN DUYSEN": "Health",
    "MIDDELARE": "Health",
    "DOKTER": "Health",
    "HELAN": "Health",
    "FARMA": "Health",
    "APOTEEK": "Health",
    "MEDINA": "Health",
    "LABO": "Health",
    "DE JAEGER MARC & VAN T": "Health",
    "UP LIFT KINE": "Health",
    "AZ SINT-LUCAS": "Health",
    "DELFORCHE": "Health",
    
    "BUY WAY SA CREDITOR": "Loan",
    "SETTLEMENT KBC CREDIT": "Loan",
    "INSTALMENT LOAN": "Loan",
    "SETTLEMENT MASTERCARD": "Loan",
    "REVOLUT": "Transfers",

    "NAPOLEON GAMES": "Leisure & Entertainment",
    "STARCASINO": "Leisure & Entertainment",
    "BOWLINGPALEIS": "Leisure & Entertainment",

    "KBC PLUS": "Other",
    "STAD LOKEREN": "Other",
    "CASH WITHDRAWAL": "Other",
    "INSTANT CREDIT TRANSFER": "Other",
    "CVO FOCUS": "Other",
    "IZ-HA": "Other",
    "ARTI": "Other",
    "ST DENIJS WES": "Other",
    "DIRK DE WITTE KAPPERS": "Other",

    "SENDING MONEY INSTANTLY": "Other",
}